### PR TITLE
Add parent_taxons / child_taxons fields to dependent expansion rules

### PR DESCRIPTION
**Pull request by mobaig**
Finding Things are building tools for editing and navigating taxonomies.
To support this, we need to be able to retrieve parts of the taxonomical
hierarchy from the publishing api.

Adding these additional fields to the expansion rules allows us to do
this efficiently, without making multiple network requests to construct
the hierarchy from the client application.

### CODE REVIEW

**Comment by MatMoore** [comment]
👍 from me but might be worth somebody more familiar with dependency resolution functionality reviewing as well?

**Comment by cbaines** [comment]
I'm not particularly familiar with the dependency resolution functionality, but, it looks like this change might also require changing the documentation?

**Comment by mobaig** [comment]
What documentation did you have in mind @cbaines ? I've added a commit which includes a pact-broker link that was missing from the `api.md` doc. Other than that, I'm not sure I've seen anything else that refers to the return values of this endpoint explicitly.

**Comment by dougdroper** [comment]
This part of dependency resolution is meant to be application specific, so no need to document in the publishing API

**Comment by MatMoore** [comment]
It might be worth documenting this in collections publisher then, since that's the publishing app for taxons.

**Pull request merged**
