### PR TITLE
Update Licence Transaction schema

### PR DESCRIPTION
**Pull request by 1pretz1**
Trello:
https://trello.com/c/zGnVczSU/1721-update-finder-content-tagging-for-licences

Failing Specialist Publisher spec as the fields have changed. We'll force the tests to pass in this PR, merge and then merge the associated Specialist Publisher branch: https://github.com/alphagov/specialist-publisher/pull/2205 (tests will pass for SP branch after this is merged).

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails upgrade.

### CODE REVIEW

**Review by KludgeKML — APPROVED** [review]
LGTM

**Comment by leenagupte** [comment]
Could you explain why the names have changed? I'm guessing that sector has changed to industry because of user research? I'm not sure why "licence_transaction" has been prepended to the other fields.

**Comment by 1pretz1** [comment]
Sure @leenagupte, sorry it wasn't clear! 

The reasoning behind the majority of the changes came from a content review of the finder by Alice. The attached [Trello card](https://trello.com/c/zGnVczSU/1721-update-finder-content-tagging-for-licences) has more information on reasoning behind the finder changes.

> I'm guessing that sector has changed to industry because of user research?

Indeed, we noticed in UR that users were more familiar with industry. 

 > I'm not sure why "licence_transaction" has been prepended to the other fields.

I noticed we have a pattern of prefixing Specialist Publisher fields with their document / finder, e.g: https://github.com/alphagov/search-api/commit/1f6d9dc4e340e0dc2542e2b44e4622966781baed or https://github.com/alphagov/search-api/blob/1af720b4ce7b86c5c7ff6f40758596c4c1b1e0d8/lib/govuk_index/presenters/elasticsearch_presenter.rb#L155-L175 and thought it's a good idea as it makes the ownership / intended purpose clear for the fields.

**Comment by leenagupte** [comment]
> https://github.com/alphagov/search-api/blob/1af720b4ce7b86c5c7ff6f40758596c4c1b1e0d8/lib/govuk_index/presenters/elasticsearch_presenter.rb#L155-L175

Ah, ok, thanks. That makes sense. I would be great if you could add this explanation to the commit message / PR description as well.

**Comment by 1pretz1** [comment]
Sure thing @leenagupte - I've also updated the other PRs to include the explanation.

**Review by leenagupte — APPROVED** [review]

**Pull request merged**
