### PR TITLE
Add landing page schema / document type

### PR DESCRIPTION
**Pull request by richardTowers**
Like the coronavirus landing page schema, this will permit details objects of any structure. This is to give us an initial blank canvas while we establish the correct content model, and may be restricted further down the line.

### CODE REVIEW

**Review by leenagupte — COMMENTED** [review]
I have a question about the description of the change which I've tagged you in elsewhere.

Also, could an example content item be added?.

**Comment by richardTowers** [comment]
Description edited.

I don't think it's worth adding an example content item until we know what the structure is going to be, no? Otherwise it'll just be a confusing / imperfect mirror of the structure we've hardcoded in frontend.

**Comment by leenagupte** [comment]
> Description edited.
> 
> I don't think it's worth adding an example content item until we know what the structure is going to be, no? Otherwise it'll just be a confusing / imperfect mirror of the structure we've hardcoded in frontend.

I meant an example for the basic content item, with an empty details hash. 

A fake content item is being duplicated in a few places in the frontend tests at the moment:

- [model spec](https://github.com/alphagov/frontend/blob/1d8104f7ebbd31c251dd1787172653d2b566738c/spec/models/landing_page_spec.rb)
- [system spec](https://github.com/alphagov/frontend/blob/1d8104f7ebbd31c251dd1787172653d2b566738c/spec/system/landing_page_spec.rb)
- [request spec](https://github.com/alphagov/frontend/blob/1d8104f7ebbd31c251dd1787172653d2b566738c/spec/requests/landing_page_spec.rb)

It'd be nicer if one example could be pulled in rather.

**Comment by richardTowers** [comment]
Ah, fair enough. Yeah, I can add that.

**Comment by richardTowers** [comment]
Moving back to draft while I investigate the failing test

**Comment by richardTowers** [comment]
Frontend tests fixed in https://github.com/alphagov/frontend/pull/4267
Unrelated whitehall tests fixed in https://github.com/alphagov/whitehall/pull/9506

Ready for review again!

**Review by leenagupte — APPROVED** [review]
Thanks for adding an example ⭐

**Pull request merged**
