### PR TITLE
Remove mapped_specialist_topic_content_id

### PR DESCRIPTION
**Pull request by unoduetre**
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

This application is owned by the publishing platform team. Please let us know in #govuk-publishing-platform when you raise any PRs.

Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails upgrade.

# Warning

The following [PR](https://github.com/alphagov/whitehall/pull/8969) in the whitehall repository must be merged first.

# What

As part of work to retire specialist topics, we temporarily stored a mapping between the archived specialist topic and its document collection conversion. We should remove this once we’re done.

# Why

To keep the system clean and avoid unnecessary data.

[Trello card](https://trello.com/c/T6GgX4Vj/2503-remove-mappedspecialisttopiccontentid-from-document-collections-m-l)

### CODE REVIEW

**Review by beccapearce — COMMENTED** [review]
This one looks good too. Again it would be great to make the commit messages distinct. (I know one is just generated), I usually just use `Run rake build_schemas` for the second commit so people know they can not pay it too much attention.

**Comment by unoduetre** [comment]
> This one looks good too. Again it would be great to make the commit messages distinct. (I know one is just generated), I usually just use `Run rake build_schemas` for the second commit so people know they can not pay it too much attention.

They are distinct, because of the second line, which is not visible by default here (you'd need to click on ...), but it is visible in the commit list.

**Comment by beccapearce** [comment]
yep yep, I see the rest of the commit message. it would be nice to have it in the title of the commit I think. Just thinking about scrolling down the commits in the [github GUI](https://github.com/alphagov/publishing-api/commits/main/) where the extended commit isn't visible by default.

**Comment by hannako** [comment]
Thanks @unoduetre it's great to see this almost gone!

You can reference that the work reverts https://github.com/alphagov/publishing-api/pull/2385

And whilst it seems like a nitpick, I do agree with Becca's comment about simple pscannable commit titles. You can see the titles for the original implementation as a guide.

**Review by beccapearce — APPROVED** [review]
Looks great to me! 💪

**Review by JonathanHallam — APPROVED** [review]
Looks good to me, thank you :)

**Pull request merged**
