### PR TITLE
Store published_at in content store for V2 content items

### PR DESCRIPTION
**Pull request by AndrewVos**
This is really just a hack to get the functionality we needed, and should probably
have some more tests. Just want to confirm that this is the correct approach.

### CODE REVIEW

**Comment by elliotcm** [comment]
Yes this seems a reasonable approach, though you might want to use `last_published_at` to differentiate from the concept of "this is when it first went live".

**Comment by gpeng** [comment]
Does it need another date field? Doesn't updated at already do this, assuming you touch the content item during the publish.

**Comment by AndrewVos** [comment]
@gpeng No updated_at doesn't do anything because the content isn't really touched during publish. I'm not explaining this well, but long story short updated_at means the last time put_content was called. In our UI this amounts to updated_at being equal to the last time the user saved a document, not the last time they clicked Publish. We need the latter displayed in our frontend.

**Comment by AndrewVos** [comment]
@elliotcm Renamed to `last_published_at`.

**Comment by gpeng** [comment]
Ok... There are quite a few dates building up around `ContentItem` that I find a bit confusing. I see you need a date that represents the last time the content item as a whole was updated (I mean, including its `State` in this case). I think there's an argument for touching the `ContentItem` when any of the associated tables ('the pillars' etc) are updated. In words, publishing a content item changes its state. I think `updated_at` should reflect that despite the fact that the state isn't stored in the same record in the DB. Obviously, if your UI needs a date the `ContentItem` itself was last saved and the date that it was published then overloading that date is no good to you, I realise that. The `State` object has timestamps too doesn't it? Would that be any good?

**Comment by AndrewVos** [comment]
The `State` object does, apparently, store these dates. This approach just seemed better than relying on some other object. A lot more obvious. I discuessed all this with @tuzz originally.

**Comment by tuzz** [comment]
The `updated_at` on the state should be the last time the state was updated. I don't think we should touch it when some other arbitrary field changes on the content item. That would seem odd?

This approach looks long the right lines to me. :+1:

**Comment by gpeng** [comment]
@tuzz I actually meant the other way around. Touching the `ContentItem` when the `State` was updated.

**Comment by boffbowsh** [comment]
But from what @gpeng is saying, couldn't `last_published_at` in the `DownstreamPresenter` simply be something like:

```ruby
state.name == "published" ? state.updated_at : nil
``` 
 
Or am I confused (again) by the data model?

**Comment by elliotcm** [comment]
@boffbowsh You could indeed do that.  I think I suggested it to someone yesterday but that might've been for something different.

**Comment by elliotcm** [comment]
@boffbowsh however, you'd have to find the published content item if you're dealing with a draft at the time.

**Comment by elliotcm** [comment]
@gpeng He doesn't need a date to represent the last time the content item was updated, he needs a date to represent the last time it was sent to the live content store.

**Comment by tuzz** [comment]
> @tuzz I actually meant the other way around. Touching the ContentItem when the State was updated.

I'm also not sure that's the right thing to do. I'd expected the updated_at on ContentItem to be the last time the content of that ContentItem was changed. For example, when a ContentItem gets "superseded" because something else has published over the top of it, I wouldn't expect that to affect its timestamps because only the state has changed. Maybe I'm missing something, though? Happy to discuss.

**Comment by elliotcm** [comment]
@AndrewVos Further to the chat above, this model might not be the best place to keep this timestamp (but maybe it is), could you pop over when you have time and we'll discuss again?

**Comment by AndrewVos** [comment]
@elliotcm working from home today, I'll catch you on slack...

**Comment by gpeng** [comment]
@tuzz Let's discuss that away from this PR as it's probably irrelevant here.

@elliotcm The `State#updated_at` would be the date it was sent wouldn't it, assuming `State#name` is 'published'?

**Comment by elliotcm** [comment]
@gpeng it would, though it would require you finding the right object.  We'll have a chat with Andrew later and figure out the specifics.

**Comment by gpeng** [comment]
@elliotcm Don't you already have the `ContentItem` passed in? ([here](https://github.com/alphagov/publishing-api/pull/229/files#diff-a8f5f38617f3679840b8740e6627ab92R47)).

**Comment by elliotcm** [comment]
@gpeng yes, but we're talking about providing this information in a GET request.

**Comment by gpeng** [comment]
🤔 Ok... not sure I understand but I'd like to if you'd fill me in (in the verbal rather than violent sense 🤓) when you've done the discussing. 👍

**Comment by AndrewVos** [comment]
@thehenster I think that's there for when the item is in draft. Also, I've written this code to only set the value in the V2 api requests, so in pre-V2 I expect the value to not be set.

**Comment by AndrewVos** [comment]
Closing this because after speaking to @elliotcm we decided this isn't needed: https://github.com/alphagov/government-frontend/pull/120

**Pull request closed without merging**
