### PR TITLE
No more redrafted

### PR DESCRIPTION
**Pull request by elliotcm**
Do not merge until cleared with @tuzz and/or specialist publisher team.

We now provide the full state history of a piece
of content, so publishing applications can use this
to decide how to refer to the state of a particular
piece of content.

https://trello.com/c/HJGyeFKu/763-simplify-state-name-presentation-small

### CODE REVIEW

**Comment by tuzz** [comment]
Could we also standardise on 'published' or do you want to do that as a separate ticket?

**Comment by elliotcm** [comment]
@tuzz https://trello.com/c/xlgfQjqB/765-simplify-state-name-presentation

**Comment by tuzz** [comment]
Looks good to me. Please don't merge/release yet. We need to coordinate this with a corresponding change to Specialist Publisher. I'll add a ticket to capture that.

**Comment by tuzz** [comment]
We have now finished integrating against this. Planning to deploy both projects simultaneously.

**Pull request merged**
