### PR TITLE
Rake task to validate version sequences

### PR DESCRIPTION
**Pull request by tuzz**
I wrote a quick thing to validate version sequences. These are most likely remnants of the race condition bug that was fixed a while ago. I haven't written any tests, but can do if we think this is a valuable thing to repeatedly run in the future.

This should help @MatMoore and @davidslv fix the problems they were seeing yesterday afternoon. We should probably add a migration to fix records with invalid version sequences.

We could also consider extended these checks to consider whether the states are valid, too. For example, we may want to validate that there is only one published and draft item.

```
$ bundle exec rake db:validate_versions

Running query...
Done. Took 7.3 seconds.

Invalid version sequence for 37c6a708-3e88-4470-9aca-81d4ba103b0a, en:
[1, "superseded", "/guidance/tick-surveillance-scheme"]
[2, "superseded", "/guidance/tick-surveillance-scheme"]
[3, "superseded", "/guidance/tick-surveillance-scheme"]
[4, "published", "/guidance/tick-surveillance-scheme"]
[4, "superseded", "/guidance/tick-surveillance-scheme"]

Invalid version sequence for 42f57c6c-dba6-486e-b266-4224fdb858e9, en:
[1, "superseded", "/guidance/contacts-phe-health-protection-teams"]
[2, "superseded", "/guidance/contacts-phe-health-protection-teams"]
[3, "published", "/guidance/contacts-phe-health-protection-teams"]
[3, "superseded", "/guidance/contacts-phe-health-protection-teams"]
[4, "draft", "/guidance/contacts-phe-health-protection-teams"]

Invalid version sequence for 5c6c8576-3cd2-4a80-b9da-bd8271ebe079, en:
[1, "superseded", "/government/publications/veterans-world"]
[2, "superseded", "/government/publications/veterans-world"]
[3, "superseded", "/government/publications/veterans-world"]
[3, "published", "/government/publications/veterans-world"]

Invalid version sequence for 5e9f05e7-7706-11e4-a3cb-005056011aef, fa:
[1, "superseded", "/government/world/iran.fa"]
[2, "superseded", "/government/world/iran.fa"]
[2, "published", "/government/world/iran.fa"]
[3, "draft", "/government/world/iran.fa"]
[3, "draft", "/government/world/iran.fa"]

Invalid version sequence for 5f4b0a93-7631-11e4-a3cb-005056011aef, en:
[1, "superseded", "/guidance/educational-psychology-funded-training-scheme"]
[2, "superseded", "/guidance/educational-psychology-funded-training-scheme"]
[3, "draft", "/guidance/educational-psychology-funded-training-scheme"]
[3, "published", "/guidance/educational-psychology-funded-training-scheme"]

Invalid version sequence for 5f4c84d3-7631-11e4-a3cb-005056011aef, en:
[1, "superseded", "/government/collections/investment-in-the-uk-guidance-for-overseas-businesses"]
[2, "published", "/government/collections/investment-in-the-uk-guidance-for-overseas-businesses"]
[3, "draft", "/government/collections/investment-in-the-uk-guidance-for-overseas-businesses"]
[3, "draft", "/government/collections/investment-in-the-uk-guidance-for-overseas-businesses"]

Invalid version sequence for 5fa75e01-7631-11e4-a3cb-005056011aef, en:
[1, "superseded", "/guidance/pupil-premium-virtual-school-heads-responsibilities"]
[2, "superseded", "/guidance/pupil-premium-virtual-school-heads-responsibilities"]
[3, "draft", "/guidance/pupil-premium-virtual-school-heads-responsibilities"]
[3, "published", "/guidance/pupil-premium-virtual-school-heads-responsibilities"]

Invalid version sequence for 6a293b0f-ba2e-4d6a-a305-a339b2e6c60f, en:
[1, "superseded", "/government/organisations/highways-england/about/access-and-opening"]
[2, "superseded", "/government/organisations/highways-england/about/access-and-opening"]
[3, "superseded", "/government/organisations/highways-england/about/access-and-opening"]
[4, "draft", "/government/organisations/highways-england/about/access-and-opening"]
[4, "published", "/government/organisations/highways-england/about/access-and-opening"]

Invalid version sequence for 919bd03c-8c0a-4aca-9350-f8427199789e, en:
[1, "withdrawn", "/government/case-studies/stuart-scott"]
[1, "published", "/government/case-studies/intellectual-property-stuart-scott"]
```

### CODE REVIEW

**Comment by MatMoore** [comment]
Nice. I was also wondering if it's possible to tighten any of the database level constraints as well? (I'm a bit late to party here I know). The thing we really want to ensure uniqueness on (content_id, number) is currently split over table boundaries (content_id, number), but should (content_item_id, number) be unique as well?

**Comment by Davidslv** [comment]
We are trying this, we will let you know soon, we think we need to apply a few changes.

**Comment by tuzz** [comment]
@MatMoore 
> I was also wondering if it's possible to tighten any of the database level constraints as well?

Absolutely. We should look at adding these. I believe we have a ticket somewhere to tighten up our validations and report on any problems. I'll see if I can dig that out.

**Comment by MatMoore** [comment]
We noticed some content ids we were expecting to be caught by this query weren't showing up.

I think it's because the duplicated versions correspond to different content items, for example a superseded edition and a live edition with the same content_id and same version. 

To catch this case, the query would need to start with each content_item row, then join in similar content_items by content_id and locale. Then from that we can join in the state information from states and user_facing_versions.

I'm experimenting with this at the moment but I don't think my query is quite correct. Let me know if you want to work on this together.

My wip is:

```sql
        select
          ci.content_id,
          t.locale,

          -- select arrays of supporting attributes
          array_agg(ci2.id) as content_items,
          array_agg(s.name) as states,
          array_agg(v.number) as versions,
          array_agg(l.base_path) as base_paths

        from content_items ci
        join translations t on t.content_item_id = ci.id

        -- join in other editions of the content, which may be superseeded
        -- these need to be the same locale
        join content_items ci2 on ci2.content_id = ci.content_id
        join translations t2 on t2.content_item_id = ci2.id and t2.locale = t.locale


        -- join supporting objects
        join states s on s.content_item_id = ci2.id
        join user_facing_versions v on v.content_item_id = ci2.id
        join locations l on l.content_item_id = ci2.id

        where ci.content_id = '502eac33-76ad-499e-b15f-a1544be548c5'

        group by ci.content_id, t.locale
```

**Comment by tuzz** [comment]
Hi @MatMoore – do you still need help?

**Comment by MatMoore** [comment]
As discussed offline, please ignore the above comment. Our problem is something different and shouldn't block this PR getting merged. :dancer:

**Comment by tuzz** [comment]
Elliot gave permission to self-merge on green.

**Pull request merged**
