### PR TITLE
Add major_published_at to Edition

### PR DESCRIPTION
**Pull request by emmabeynon**
https://trello.com/c/lGZFJaDB/1020-2-additional-publishing-api-date-fields

### CODE REVIEW

**Comment by kevindew** [comment]
How does this fit in with temporary_major_published_at ? I assume we need one of them rather than both - but I might be missing something

**Comment by emmabeynon** [comment]
> How does this fit in with temporary_major_published_at ? I assume we need one of them rather than both - but I might be missing something

My understanding from our chat earlier was that `temporary_major_published_at` would be set to the previous item’s `major_published_at`, which we don’t have at the moment.

**Comment by kevindew** [comment]
> My understanding from our chat earlier was that temporary_major_published_at would be set to the previous item’s major_published_at, which we don’t have at the moment.

Gotcha... Yeah that would be the same value as temporary_major_published_at, so I guess either we'd want to alias the `major_published_at` method to point to `temporary_major_published_at` or to replace `temporary_major_published_at` with `major_published_at`.

We have same situation with `published_at` as well I guess, where it has a `temporary_` prefix in the db but doesn't conflict with another name so may not actually need it.

**Comment by emmabeynon** [comment]
> Gotcha... Yeah that would be the same value as temporary_major_published_at, so I guess either we'd want to alias the major_published_at method to point to temporary_major_published_at or to replace temporary_major_published_at with major_published_at.

I think it's probably easiest to rename `temporary_major_published_at` to `major_published_at`.  What do you think?

**Comment by emmabeynon** [comment]
Closed in favour of https://github.com/alphagov/publishing-api/pull/1022

**Pull request closed without merging**
