### PR TITLE
[WIP] Use Sentry for error reporting

### PR DESCRIPTION
**Pull request by tijmenb**
https://trello.com/c/2AP3O9dn

### CODE REVIEW

**Comment by thomasleese** [comment]
🤖 🤖 🤖 ✅

**Comment by thomasleese** [comment]
I realise this is WIP so perhaps it's not a concern, but is there a suitable replacement for `Airbrake.notify_sync`? We use it in the consistency checker to ensure the error makes it through to Errbit at the moment (as it's the last thing the process does so we found the process was terminating before sending the error). Perhaps this isn't a problem with `raven-ruby`.

**Comment by thomasleese** [comment]
Ignore that... I can see there is. Not sure how I missed it the first time.

**Comment by tijmenb** [comment]
Hmm, that's interesting. Raven does sync by default as far as I know, so we wouldn't need this? 

Btw `GOVUK::Error.notify_sync` doesn't actually exist, that's sloppy review on my part.

**Comment by thomasleese** [comment]
Ah! Yeah, if it's synchronous by default then we wouldn't need it, but then I wonder if we would want that behaviour by default since it's that's different to how `Airbrake.notify` currently works?

**Comment by tijmenb** [comment]
I'm tempted to go with Sentry's default behaviour until we see a problem. Does that sounds allright?

**Comment by thomasleese** [comment]
Yep, fine by me 👍

**Pull request closed without merging**
