### PR TITLE
Add RabbitMQ production config

### PR DESCRIPTION
**Pull request by alexmuller**

### CODE REVIEW

**Comment by boffbowsh** [comment]
I assume the env var is set in the environments? If so, 👍

**Comment by alexmuller** [comment]
Not yet, was planning to set it if nobody was too offended by this pull request.

**Comment by kevindew** [comment]
Does this mean we'll lose the magic file that's inserted as part of deployment? if so 🎉

**Comment by alexmuller** [comment]
Once https://github.com/alphagov/govuk-puppet/pull/4876 is in production this can be merged.

**Comment by alexmuller** [comment]
This is ready, you can verify it with:

```
fab staging class:backend do:'cat /etc/govuk/publishing-api/env.d/RABBITMQ_PASSWORD'
fab production class:backend do:'cat /etc/govuk/publishing-api/env.d/RABBITMQ_PASSWORD'
```

**Pull request merged**
