### PR TITLE
Add Jenkinsfile and update build script

### PR DESCRIPTION
**Pull request by carlosmartinez**
Moving to Jenkins 2, which takes care of Git status.

### CODE REVIEW

**Comment by kevindew** [comment]
Neat - is Jenkins 2 running now or is this pre-emptive of that?

**Comment by carlosmartinez** [comment]
@kevindew - https://ci.integration.publishing.service.gov.uk/job/publishing-api/job/add-jenkinsfile/

**Comment by kevindew** [comment]
@carlosmartinez cool - It looks good to me, but I assume once it's merged it breaks on existing CI. Do we need to worry about that? or do we need an intermediary step?

**Comment by carlosmartinez** [comment]
@kevindew yes, probably best to hold off merging it until further discussion

**Comment by danielroseman** [comment]
Is there anything stopping this being merged now so that we can switch over to Jenkins 2?

**Pull request closed without merging**
