### PR TITLE
Remove duplicate drafts for specialist publisher.

### PR DESCRIPTION
**Pull request by elliotcm**
https://trello.com/c/Yi7hf3X2/696-remove-unchanged-drafts-created-by-refactoring-medium

A bunch of these were created a while ago when we
restructured the database.  They need to go away
so that things don't show as "redrafted" when they
aren't really.

Before:
```
ContentItemFilter.new(scope: ContentItem.where(publishing_app: "specialist-publisher")).filter(state: "draft").count
=> 14915

ContentItemFilter.new(scope: ContentItem.where(publishing_app: "specialist-publisher")).filter(state: "published").count
=> 14907
```

During:
```
Deleting duplicate draft #226681 (822793c7-8de7-4a8c-9e36-fb6382653f13)
Deleting duplicate draft #242045 (3545fbfb-e7e6-4e2f-91e7-2d73f32d66d1)
Deleting duplicate draft #218245 (2f67c0bc-f233-4b29-9896-3aa9325ce91a)
Deleting duplicate draft #242011 (fa51c092-6c89-4bca-a7b2-56298d982668)
Deleting duplicate draft #238733 (b105be13-fa2e-40e3-9e2c-78c30c05756a)
Deleting duplicate draft #219426 (26ab73b7-ebdf-448c-9115-144f44a7d20d)
Deleting duplicate draft #215763 (b90e4d4b-9eb3-46aa-b96f-b757a373ee0d)
Deleting duplicate draft #352104 (437d45e8-57d3-46e4-99a0-a8fb4e84176a)

... many others ...

Deleting duplicate draft #241838 (65641676-df3e-43d1-a6e7-28388c0d4b8e)
Deleting duplicate draft #214539 (b2e56ce8-27a2-4088-a3ea-f164e521a97f)
Deleting duplicate draft #223915 (a230d49a-71f7-460a-98b6-130aa88d9e9b)
Deleting duplicate draft #296774 (b5a8ea2b-1d80-405d-be45-21b7efc2e49b)
Deleting duplicate draft #218202 (b6f308a6-cb0a-4038-9fb7-02c61e14e270)
Deleting duplicate draft #216714 (022d3e97-217e-48e6-927b-3422f2dd9e53)
Deleting duplicate draft #221853 (9bbbe725-8892-4115-bf20-8fc1d8876002)
Deleting duplicate draft #243204 (7b72a778-95b7-4bb4-a093-dd1aa0e7ae77)
```

After:
```
ContentItemFilter.new(scope: ContentItem.where(publishing_app: "specialist-publisher")).filter(state: "draft").count
=> 694

ContentItemFilter.new(scope: ContentItem.where(publishing_app: "specialist-publisher")).filter(state: "published").count
=> 14907
```

### CODE REVIEW

**Comment by elliotcm** [comment]
@benilovj @tuzz Could your team confirm that this is the right number of drafts to be left over?  (these numbers based on a bit of an old dataset)

**Comment by tuzz** [comment]
Had a look in specialist-publisher after a data replication and we get these numbers:

```
SpecialistDocumentEdition.where(state: "draft").count
#=> 617

SpecialistDocumentEdition.where(state: "published").count
#=> 14788
```

So those numbers reported seem like the right ballpark. Your numbers are higher, too, which seems safer.

**Comment by elliotcm** [comment]
OK.  Once this is on integration I'll check again against specialist publisher.

**Comment by danielroseman** [comment]
Are there any other document types we should be checking? Although specialist-publisher is most visibly affected because it's using the publishing-api to show the state of all its content items, it seems likely that the duplicate draft issue exists for other content too, which might have undesirable effects further down the line.

**Comment by elliotcm** [comment]
@danielroseman Yeah that occurred to me too.  Perhaps we should do this one which is relatively well contained, and once everyone's happy with it adjust the rake task to run on everything.

**Comment by elliotcm** [comment]
Though that said, any brand new drafts will be caught by this, so requires a bit of careful thought.

**Comment by elliotcm** [comment]
@danielroseman I've restricted this run to the period around the migration and updated the output above.

Seems to have had much the same effect and was much quicker to run.

**Pull request merged**
